### PR TITLE
Disable Microsoft Office 2019 telemetry

### PR DESCRIPTION
**Pull request by tomasz1986**
Disable the following scheduled tasks responsible for scanning and uploading
user data to Microsoft.

Office ClickToRun Service Monitor: This task monitors the state of your
Microsoft Office ClickToRunSvc and sends crash and error logs to Microsoft.

OfficeTelemetryAgentLogOn2016: This task initiates Office Telemetry Agent,
which scans and uploads usage and error information for Office solutions when
a user logs on to the computer.

OfficeTelemetryAgentFallBack2016: This task initiates the background task for
Office Telemetry Agent, which scans and uploads usage and error information
for Office solutions.

Signed-off-by: Tomasz Wilczyński <twilczynski@naver.com>

### CODE REVIEW

**Comment by tomasz1986** [comment]
Strictly speaking, Office is not a part of Windows, so I will definitely understand if you decide not to include the scripts related to it in Win10-Initial-Setup-Script. However, Office is used and installed together with Windows in many environments, and I believe that having their telemetry bound together will be useful for quite a large number of users.

Also, do not be misled by "2016" in the names, as these tasks are created by Office 2019 upon its installation.

**Comment by r3incarnat0r** [comment]
I often use similar tweak (it also contains GPOs and it's Office 2013-2019 compatible). It's one of the tweaks in my separate library module designed as an extension for this project, but I haven't polished and released it yet, as I'm kinda waiting for version 4, so I wouldn't do things (i.e. adopting to project's conventions etc.) twice. :)
But if @Disassembler0 would say he's not gonna make it let's say in the next few months or even at all, I might look at it sooner.

**Comment by Disassembler0** [comment]
I'm definitely not gonna make in next few months, @r3incarnat0r, so feel free to go ahead.

And yes, initially I was gonna reject it because Office aren't part of Win10, but I guess if we make it as completely separate tweak library, I'll probably survive it.

**Comment by tomasz1986** [comment]
I have no objections for having the tweaks related to other Microsoft products listed in a separate library.

For now, I have not been able to find any decent open source scripts or tools dealing with them, hence I pushed this commit here. They are usually included either in much larger scripts, which are usually not documented, not maintained, and very messy (unlike this one), or are a part of various closed source tools, which I am not willing to use.

**Comment by rnc** [comment]
Out of curiosity what is the status of the PR ?

**Comment by undergroundwires** [comment]
@tomasz1986 Thanks for this awesome tweak 🙏🏿. Took a a while and googling before I found this PR. I integrated it in [privacy.sexy](https://github.com/undergroundwires/privacy.sexy), I'm also working on reverting toggle functionality once it's done I'll add way to enable it as well. 

Btw I couldn't not find any well-maintained & open source tool dealing with applications on OS either and that's why I built [privacy.sexy](https://github.com/undergroundwires/privacy.sexy). Feel free to check out for more telemetry disabling for applications, and also I'm accepting PR refugees if anyone wants to contribute anything 😊

**Comment by undergroundwires** [comment]
@tomasz1986 Thanks for this awesome tweak 🙏🏿. Took a a while and googling before I found this PR. I integrated it in [privacy.sexy](https://github.com/undergroundwires/privacy.sexy), I'm currently working on reverting toggle functionality once it's done I'll add way to enable it as well.

Btw I couldn't not find any well-maintained & open source tool dealing with applications on OS either and that's why I built [privacy.sexy](https://github.com/undergroundwires/privacy.sexy). Feel free to check out for more telemetry disabling for applications, and also I'm accepting PR refugees if anyone wants to contribute anything 😊

**Pull request merged**
