### PR TITLE
Add Lenovo AppxPackage bloatware

### PR DESCRIPTION
**Pull request by agsimmons**
There are also some Lenovo bloat applications I have on a new system that are not included in the output of "Get-AppxPackage -AllUsers". Is there a standard way to find and remove these through powershell, and are they wanted for this project? As far as I can tell, only Appx packages are dealt with so far.

### CODE REVIEW

**Comment by Disassembler0** [comment]
Were your Windows preinstalled on a newly bought Lenovo laptop or did you install them yourself from a separate medium? From what you're saying it sounds like the former, but it's entirely possible that MSFT has some agreement which allows to ~~infest~~ customize Lenovo laptops even further.

**Comment by agsimmons** [comment]
@Disassembler0 These packages were pre-installed on newly bought Lenovo all-in-ones. I thought Dell was bad, but then I set up these Lenovos..

**Comment by Disassembler0** [comment]
Yeah, I feel for you. I remember taking care of a herd of Y580s several years ago. Not only I had to get rid of most of the software, but I had to throw out even hardware (the mSATA SSD module which was supposed to serve as HDD cache extension). Only then it finally worked acceptably.

I'll accept the PR as the extra AppX will simply be ignored on laptops where they don't exist, but I can't accept any further tweaks for apps deviating from the original untainted clean Windows installation. Otherwise the script would have to be simplified just to `format c:` :)

**Comment by agsimmons** [comment]
@Disassembler0 I guess I misunderstood the "Third Party" part of "UninstallThirdPartyBloat". I figured it would also include bloat from manufacturers like Dell and Lenovo. Would it make sense to have another function to remove manufacturer bloat?

**Comment by Disassembler0** [comment]
*Third party* as in *not published Microsoft*.

> Would it make sense to have another function to specifically remove manufacturer bloat?

Not really. Every manufacturer, every product line, every type and sometimes even the same type throughout the time may have something extra what's not present anywhere else. I don't want the script to become a freak show. As per FAQ - *The default is considered freshly installed Windows 10 or Windows Server 2016 with no adjustments made during or after the installation.* Customization by the  manufacturer or distributor already constitutes as *adjustments made during or after the installation*, although not done by the user directly.

However you're more than welcome to keep the tweaks for the particular models in your forks. That should become even more easier once I chew through #81.

**Pull request merged**
