### PR TITLE
Added control for item selections using checkboxes in explorer

### PR DESCRIPTION
**Pull request by Tikus**
Hi,
please commit if you find it usefull.

Thank you
Tom

### CODE REVIEW

**Comment by chiva** [comment]
Hello @Tikus,

I'm currently running the script as a 2 part login script in a GPO:
1. All mods that need admin rights, are run as a computer startup script
2. The rest of the mods, that affect the user, are run as a user login script

The second part is run as a user login script as if run as a computer startup script it would run as the administrator user, so it won't affect the logged in user.
Do you have experience when running this modification as a computer startup script? Will it modify the logged in user hive or will it continue modifying the admin one?

It would be great if this allows the script to be run all at once instead of having to split it.

**Comment by Tikus** [comment]
Hi there,

Im using this script for 2 scenarios:

1. As part of MDT task sequence that setups defaults for the computer
Its used with -useDefaultUser option. In this mode it writes to c:\users\Default\ntuser.dat so any user created afterwards will inherit those settings automatically.

2. As a script that i execute under real users that tunes the rest (settings are different for some users)
In this mode HKCU is mapped to HKEY_USERS\$currentUserSid so settings dont apply to admin but logged in user.

So yes you can run this script only once. Another benefit is that the user doesnt have to be in admin group. 

Let me know if it works for you

**Comment by chiva** [comment]
When running the script as a computer start script or a scheduled task gpo (at the computer tree) with the user to run as SYSTEM, the $env:USERNAME returns the PC itself (eg TESTPC$) so it can't find the user sid and stays null.

How do you run it?

Thanks!

**Comment by Tikus** [comment]
I alway run the script as local administrator. If u run it as system user on system where no local user exists  you could try adding -useDefaultUser argument as it would write to registry of default user so any local user created afterwards will inherit those settings. Script expects that there is some user logged in already.

**Comment by chiva** [comment]
The script is run on a system with a domain user that has already logged-in in the past, and the script is run as a user login script (through the task scheduler) for that user but executed as the SYSTEM user for admin rights.
It should run after the user logs in, but it doesn't seem to be able to get the username variable of the user instead of the computer.

I can't make it work, so I think I will resort back to splitting the presets and run them separate on a user or computer GPO which worked correctly.

Thank you for your time @Tikus

**Comment by Disassembler0** [comment]
Since you're trying to merge your master instead of creating feature branches for PR, I can't pull this PR anymore, so I'll close it. Nevertheless, when I'll find some time, I'll skim through your changes as some of them look really interesting. Thanks.

**Comment by Tikus** [comment]
Sry, gotta learn git well first :( Ill be back :)

**Pull request closed without merging**
