### PR TITLE
Breakout Setting Methods

### PR DESCRIPTION
**Pull request by Calthron**
Break out the setting methods from the main script for ease of adding
new functionality.

### CODE REVIEW

**Comment by Disassembler0** [comment]
Check #81 and the [includes branch](https://github.com/Disassembler0/Win10-Initial-Setup-Script/tree/includes). Adding new functionality is possible there using `-include` command line parameter - see [relevant documentation](https://github.com/Disassembler0/Win10-Initial-Setup-Script/tree/includes#includes).

**Comment by Calthron** [comment]
The problem for me with the current approach is the base Win10.ps1 script wants to execute as soon as it is loaded, which makes the many useful configuration functions impossible to use in a more complex powershell-based installer creator and platform configuration solution.  I would like to help identify and add more useful functions to the script library you've started.

**Comment by kroimon** [comment]
I actually like this idea a little more than #81 as it separates the function definitions from the execution logic and improves reusability of the functions without forcing the user to use the default execution and command line handling code.

With this, you could even replace the preset files with standalone .ps1 scripts just containing a list of function calls. (The current preset files are interpreted line-by-line using Invoke-Expression anyway, so there's not much difference from ps1 files.)

**Comment by Disassembler0** [comment]
From technological standpoint, I like the idea of separation for all the reasons already listed. However at the same time, I need to keep in mind also the BFUs for whom right clicking and confirming an UAC prompt is a pinnacle of their technical skills. I'm inclining towards merging, but I need to think about the possible consequences a bit more.

**Comment by r3incarnat0r** [comment]
I'd also support such modularization in general. I'd suggest to move functions to (scriptname).psm1 module and use the capability from includes branch (#81) simultaneously.

I'd go even further and keep functions lists in separated files only, i.e. remove default preset from Win10.ps1. Also this long list is a bit annoyning residing at the start of the script. ;) Regulating the script too much in favour of BFUs could be quite a limiting factor for making future technical capabilities. I don't see any problem with BFUs and their pinnacle of skills anyway, they can still have their default launcher. Main script should naturally become harmless doing nothing without specifying what to do.

**Comment by Disassembler0** [comment]
Since I have all the people asking for pretty much the same features in this thread, I'll write here instead of continuing in #81 and #115.

Please check the branch [includes](https://github.com/Disassembler0/Win10-Initial-Setup-Script/tree/includes) which I have updated a few minutes ago. It combines both the changes which this PR aimed to introduce and the request for custom tweaks as discussed in #81.

The main loop in *Win10.ps1* now contains only the logic for parsing command line parameters and preset files and a single function for administrator privileges elevation. That function is specifically tailored for the script as it uses variables set during parsing, so it doesn't make sense to have it separated. Everything what was in the `$tweaks` array with the default preset has been moved to *Default.preset* file and all the tweak functions have been moved to *Win10.psm1* file. If you now run *Win10.ps1* alone without any parameters, it does exactly nothing.

The minimal params which you have to supply now for the PowerShell command to do *something* are
 - the main loop - *Win10.ps1*
 - the tweak library - e.g. *Win10.psm1*
 - the preset - e.g. *Default.preset*

Some more info about the command line parameters and general usage can be found in [Advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/includes/README.md#advanced-usage) section of the *includes* branch.

Let me know if it suit your needs or if you're still missing some important features. If there won't be any strong objections, I'm planning to merge it to the master later this week.

**Comment by r3incarnat0r** [comment]
🥇 This is just sooo awesome! Thanks!

**Comment by Disassembler0** [comment]
This PR has been reimplemented as part of 1e977ab95fe04a99cdd152d342586de01d0aec96. Thanks everyone for suggestions.

**Pull request closed without merging**
