### PR TITLE
Add bloat apps to install/uninstall

### PR DESCRIPTION
**Pull request by jnslmk**
Added both msft and third party apps to list of bloat apps to be removed.
Replaced all king.com.<app> entries with king.com.* to uninstall all apps from king.com

### CODE REVIEW

**Comment by jnslmk** [comment]
Just read your comment on my other pull request. Going to reimplement the changes using your way.
Let me know what you think about replacing the king.com.<app> entries with king.com.*

**Comment by Disassembler0** [comment]
Wow. That's a whole lot of crapware. In which Windows edition or language mutation are these installed by default? The inclusion of Xing suggest German.

**Comment by jnslmk** [comment]
I am running Win10 Home with region and language set to germany/german on installation. As installation medium I used Microsoft's media creation tool.

**Comment by Disassembler0** [comment]
Okay. So out of curiosity I've just installed Windows 10 Home de_DE and left it sitting for a while until all the provisioning finished. This is what I ended up with: [appx-de_DE.txt](https://github.com/Disassembler0/Win10-Initial-Setup-Script/files/1902917/appx-de_DE.txt)

From your list, I see there just `Microsoft.WindowsCalculator` (which is left on purpose as there is no non-AppX equivalent bundled in Windows by default) and `XINGAG.XING` which *is* a legit bloat and should be removed.

Any ideas from where you got the rest? Were they really installed as part of provisioning or did you got them in some other way? Weren't they just "suggestions" in start which would install only after you really click on them? Did you using Microsoft or local account during the post-installation setup?

**Comment by agsimmons** [comment]
@Disassembler0 I've seen DB6EA5DB.CyberLinkMediaSuiteEssentials installed on Dell desktops with pre-installed Windows 10 Pro. I haven't seen the other ones installed by default.

**Comment by jnslmk** [comment]
Thank you for checking that. This must have been a mistake on my side. When I started working on a personal windows setup script I searched for already existing projects which I combined in a personal repository. Because I didn't create a proper fork at the time I am trying to group and contribute my additions.

The apps I listed are the ones I found on my system and those I found at https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/remove-default-apps.ps1.

At the time I implemeted the changes I did not see that some of the apps showing up in the start menu were merely suggestions. As a result some of my additions might not be necessary.

**Pull request closed without merging**
